### ISSUE TITLE
Use with Airsonic-Advanced

### ISSUE THREAD

**Issue by spongle70** [simojenki/bonob#100]
Hi @simojenki 

Thanks for creating this!

Do you have any plans to make it work with Airsonic-Advanced? The current state of Gonic and Navidrome do not meet my needs.

I tried the using bonob and airsonic-advanced and get the attached errors.

[errors.txt](https://github.com/simojenki/bonob/files/8341763/errors.txt)

The docker-compose file is:

```
version: "3"
services:
  bonob:
    image: simojenki/bonob:latest
    container_name: bonob
    restart: unless-stopped
    network_mode: "host"
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4534:4534"
    environment:
      BNB_PORT: 4534
      # ip address of your machine running bonob
      BNB_URL: http://10.168.0.123:4534
      BNB_SECRET: "changeme"
      BNB_SONOS_AUTO_REGISTER: "true"
      BNB_SONOS_DEVICE_DISCOVERY: "true"
      BNB_SONOS_SERVICE_ID: 246
      BNB_SUBSONIC_URL: http://10.168.0.123:4040
      # ip address of one of your sonos devices
      #BNB_SONOS_SEED_HOST: 192.168.1.121

```
