### ISSUE TITLE
Unable to play 'Song' access denied

### ISSUE THREAD

**Issue by davidakerr** [simojenki/bonob#101]
I have Navidrome installed and working in the web UI, bonob is installed and i have it linked to my sonos application. I can browse all my music but when I select one I get an error "Unable to play 'song' access denied.  Any ideas where I'm going wrong ?

```yaml
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1040:100
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LOGLEVEL: info  
    volumes:
      - /volume1/music:/music:ro
      - /volume1/docker/navidrome:/data
  bonob:
    image: simojenki/bonob:latest
    container_name: bonob
    user: 1040:100
    ports:
      - "4534:4534"
    restart: unless-stopped
    environment:
      BNB_PORT: 4534
      BNB_URL: http:/192.168.0.100:4534  
      BNB_SECRET: psswrd-is-lik2e-this-aye
      BNB_SONOS_AUTO_REGISTER: "true"
      BNB_SONOS_DEVICE_DISCOVERY: "true"
      BNB_SONOS_SERVICE_ID: 246
      BNB_SONOS_SEED_HOST: 192.168.0.18
      BNB_SUBSONIC_URL: http://192.168.0.100:4533
      TZ: Europe/London
```
