### ISSUE TITLE
EHOSTUNREACH

### ISSUE THREAD

**Issue by phillprice** [simojenki/bonob#110]
Hello
I'm using this configuration 

```
version: '3.3'
services:
    bonob:
        network_mode: host
        environment:
            - BNB_PORT=4534
            - BNB_URL=http://<local machine>:4534  
            - BNB_SECRET=<secret>
            - BNB_SONOS_SERVICE_ID=246
            - BNB_SONOS_SEED_HOST=<sonos ip>
            - BNB_SUBSONIC_URL=<navidrome url>
        ports:
            - '4534:4534'
        image: simojenki/bonob
```
(Ive also tried without `network_mod:host`)

Unfortunately I always seem to get problems contacting the sonos device.  I've use console on the box and for some reason it can't `curl` to the sonos (even though I can from my machine outside of docker)

```
bonob-bonob-1  | {"message":"Starting bonob with config {\"port\":4534,\"bonobUrl\":{\"url\":\"http://<sonos IP>:4534/\"},\"secret\":\"*******\",\"authTimeout\":\"1h\",\"icons\":{},\"sonos\":{\"serviceName\":\"bonob\",\"discovery\":{\"enabled\":true,\"seedHost\":\"<sonos IP>\"},\"autoRegister\":false,\"sid\":246},\"subsonic\":{\"url\":\"<navidrome url>\"},\"scrobbleTracks\":true,\"reportNowPlaying\":true}","level":"info","service":"bonob","timestamp":"2022-10-15 11:58:21"}
bonob-bonob-1  | {"message":"Trying to discover sonos devices using seed <sonos IP>","level":"info","service":"bonob","timestamp":"2022-10-15 11:58:21"}
bonob-bonob-1  | {"message":"Listening on 4534 available @ http://<sonos IP>:4534/","level":"info","service":"bonob","timestamp":"2022-10-15 11:58:22"}
bonob-bonob-1  | {"service":"bonob","cause":{"message":"request to http://<sonos IP>:1400/ZoneGroupTopology/Control failed, reason: connect EHOSTUNREACH <sonos IP>:1400","type":"system","errno":"EHOSTUNREACH","code":"EHOSTUNREACH"},"level":"error","message":"Failed looking for sonos devices","timestamp":"2022-10-15 11:58:25"}
```
