### ISSUE TITLE
problem starting up

### ISSUE THREAD

**Issue by tgray** [simojenki/bonob#127]
This isn't a bug report or anything, just having issues installing and running bonob.  I'm using the docker-compose setup file from the readme.  I can login to and play music from navidrome.  When I go to try to pull up bonob in the browser, it doesn't connect.  I'm running on a raspberry pi 4.

Docker ps shows things like 
```
simojenki/bonob:latest    "docker-entrypoint.s…"   7 minutes ago   Restarting (132) 29 seconds ago.
```

Looking at the docker log I just see a bunch of entries that say 
```
Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.`
```

Seems like bonob is having issues starting up?  I don't know much about docker, so there's that too.

docker-compose file for bonob looks like this:
```  
bonob:
    image: simojenki/bonob:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4534:4534"
    restart: unless-stopped
    environment:
      BNB_PORT: 4534
      # ip address of your machine running bonob
      BNB_URL: http://10.0.1.2:4534  
      BNB_SECRET: changeme
      BNB_SONOS_AUTO_REGISTER: "true"
      BNB_SONOS_DEVICE_DISCOVERY: "true"
      BNB_SONOS_SERVICE_ID: 246
      # ip address of one of your sonos devices
      BNB_SONOS_SEED_HOST: 10.0.1.52
      BNB_SUBSONIC_URL: http://navidrome:4533
```

Any ideas?
