### ISSUE TITLE
TypeError: Cannot read undefined when logging in

### ISSUE THREAD

**Issue by Uzlkav** [simojenki/bonob#222]
Running bonob from a docker container (same one I have navidrome in). Here's my configuration:

```
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_BASEURL: /navidrome
      ND_LOGLEVEL: info
      ND_CONFIGFILE: /data/navidrome.toml
    volumes:
      - "/path:/data"
      - "/path2:/music:ro"
  bonob:
    image: simojenki/bonob:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4534:4534"
    restart: unless-stopped
    environment:
      BNB_PORT: 4534
      # ip address of your machine running bonob
      BNB_URL: http://placeholder:4534
      BNB_SECRET: "secret"
      BNB_SONOS_AUTO_REGISTER: "true"
      BNB_SONOS_DEVICE_DISCOVERY: "true"
      BNB_SONOS_SERVICE_ID: 246
      # ip address of one of your sonos devices
      BNB_SONOS_SEED_HOST: placeholder
      BNB_SUBSONIC_URL: http://placeholder:4533
      BNB_SCROBBLE_TRACKS: "true"
      BNB_REPORT_NOW_PLAYING: "true"
      TZ: placeholder
```

I have tried logging in with the admin account for the navidrome instance as well as with the credentials for a 'bonob' account that I set up, using the BNB_SECRET as the password.

Here's the full error I get:

```
Login failed!

TypeError:
Cannot read properties of undefined (reading 'error')
```

I looked at https://github.com/simojenki/bonob/issues/169 but that seems to have been fixed and adding/removing a trailing slash doesn't seem to have an effect.

Looking at the logs, nothing jumps out at me but I wouldn't know what to look for.
