### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by g0rge0us** [simojenki/bonob#97]
Hello @simojenki!

I really want to enjoy your interesting solution on my Sonos system, but when I try to deploy that as a stack on Portainer 2.11.0, running on a host OS DietPi on RPI4 (4GB RAM) with Docker + Portainer, I am getting the following error in Portainer:

_Deployment error
failed to deploy a stack: services.bonob.environment.BNB_SONOS_AUTO_REGISTER must be a string, number or null_

Here is the docker compose file/stack that I am using:
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 #should be owner of volumes
    ports:
      - "8091:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 4h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/mnt/sd200gb/appdata/navidrome:/data"
      - "/mnt/storage/music:/music:ro"
  bonob:
    image: simojenki/bonob:latest
    user: 1000:1000 #should be owner of volumes
    ports:
      - "4534:4534"
    restart: unless-stopped
    environment:
      BNB_PORT: 4534
      # ip address of your machine running bonob
      BNB_URL: http://10.0.0.4:4534
      BNB_SECRET: changeme
      BNB_SONOS_AUTO_REGISTER: true
      BNB_SONOS_DEVICE_DISCOVERY: true
      BNB_SONOS_SERVICE_ID: 246
      # ip address of one of your sonos devices
      BNB_SONOS_SEED_HOST: 10.0.0.81
      BNB_SUBSONIC_URL: http://navidrome:4533
```
I can't understand how "true" is not considered as string.
Your help is very much appreciated!
Many thanks in advance!
